spring:
  datasource:
    username: root
    password: NBY2000NBY
    url: jdbc:mysql://127.0.0.1:3306/testbase?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver